namespace FacebookSDK
{
    runtimeclass ColorLuminosityConverter : Windows.UI.Xaml.Data.IValueConverter
    {
		ColorLuminosityConverter();
		Windows.UI.Color ApplyFactor(Windows.UI.Color color, Double factor);
    }
}
