import "JsonClassFactory.idl";
import "FacebookResult.idl";

namespace FacebookSDK
{
	runtimeclass FacebookPaginatedArray
	{
		FacebookPaginatedArray(
			String request,
			Windows.Foundation.Collections.PropertySet parameters,
			JsonClassFactory objectFactory
		);

		Windows.Foundation.IAsyncOperation<FacebookResult> FirstAsync();
		Windows.Foundation.IAsyncOperation<FacebookResult> NextAsync();
		Windows.Foundation.IAsyncOperation<FacebookResult> PreviousAsync();

		Windows.Foundation.Collections.IVectorView<Object> Current { get; };
		String CurrentDataString { get; };
		Boolean HasCurrent { get; };
		Boolean HasNext { get; };
		Boolean HasPrevious { get; };

		Windows.Foundation.Collections.IVectorView<Object>
		ObjectArrayFromWebResponse(
			String response,
			JsonClassFactory classFactory
		);
	}
}
