import "FacebookResult.idl";

namespace FacebookSDK
{
	delegate Windows.Foundation.Uri DialogUriBuilder(Windows.Foundation.Collections.PropertySet Parameters);

	[default_interface]
	runtimeclass FacebookDialog : Windows.UI.Xaml.Controls.UserControl
	{
		FacebookDialog();
		void InitDialog();
		void UninitDialog();

		static String GetFBServerUrl();

		Windows.Foundation.IAsyncOperation<FacebookResult> ShowLoginDialogAsync(
			Windows.Foundation.Collections.PropertySet parameters
		);

		Windows.Foundation.IAsyncOperation<FacebookResult> ShowFeedDialogAsync(
			Windows.Foundation.Collections.PropertySet parameters
		);

		Windows.Foundation.IAsyncOperation<FacebookResult> ShowRequestsDialogAsync(
			Windows.Foundation.Collections.PropertySet parameters
		);

		Windows.Foundation.IAsyncOperation<FacebookResult> ShowSendDialogAsync(
			Windows.Foundation.Collections.PropertySet parameters
		);

		/*! discussion The current session in webview is required only if the access token is valid
		 *  When the access token is removed the cookies must be clean up
		 */
		static void DeleteCookies();
	}
}
