import "FacebookError.idl";
import "Generated/Graph.FBUser.idl";
import "FacebookPermissions.idl";

namespace FacebookSDK
{
	delegate void FacebookLoginErrorHandler(FacebookLoginButton sender, FacebookError error);

	delegate void FetchedUserInfoHandler(FacebookLoginButton sender, FacebookSDK.Graph.FBUser userInfo);

	delegate void ShowingLoggedInUserHandler(FacebookLoginButton sender);

	delegate void ShowingLoggedOutUserHandler(FacebookLoginButton sender);

	runtimeclass FacebookLoginButton : Windows.UI.Xaml.Controls.Button
	{
		FacebookLoginButton();

		FacebookPermissions Permissions{ get; set; };

		//! Ask for read permissions at login
		void InitWithPermissions(FacebookPermissions permissions);

		event FacebookLoginErrorHandler FacebookLoginError;
		event FetchedUserInfoHandler FetchedUserInfo;
		event ShowingLoggedInUserHandler ShowingLoggedInUser;
		event ShowingLoggedOutUserHandler ShowingLoggedOutUser;
	}
}
