import "FacebookPermissions.idl";

namespace FacebookSDK
{
	runtimeclass FacebookAccessTokenData
	{
		static FacebookAccessTokenData FromUri(Windows.Foundation.Uri Response);
		FacebookAccessTokenData(String AccessToken, Windows.Foundation.DateTime Expiration);
		FacebookAccessTokenData(String AccessToken, Windows.Foundation.DateTime Expiration, Windows.Foundation.DateTime DataAccessExpiration);

		String AccessToken{ get; };
		Windows.Foundation.DateTime ExpirationDate{ get; };
		Windows.Foundation.DateTime DataAccessExpirationDate{ get; };
		FacebookPermissions GrantedPermissions{ get; };
		FacebookPermissions DeclinedPermissions{ get; };
		Boolean IsExpired{ get; };
		Boolean IsDataAccessExpired{ get; };
		Boolean HasDataAccessExpired{ get; };
		void SetPermissions(Windows.Foundation.Collections.IVectorView<Object> perms);
	}
}
