namespace FacebookSDK
{
	runtimeclass FacebookMediaObject
	{
		FacebookMediaObject();
		String ContentType{ get; set; };
		String FileName{ get; set; };
		FacebookMediaObject SetValue(UInt8[] value);
		UInt8[] GetValue();
	}
}
