namespace FacebookSDK
{
	runtimeclass FacebookFeedRequest
	{
		FacebookFeedRequest();
		String PostId{ get; };
		static FacebookFeedRequest FromFeedDialogResponse(Windows.Foundation.Uri response);
	}
}
