import "FacebookAccessTokenData.idl";
import "FacebookResult.idl";
import "Generated/Graph.FBUser.idl";
import "FacebookPermissions.idl";
import "FacebookDialog.idl";

namespace winsdkfb
{
	enum SessionDefaultAudience {
		None = 0,
		OnlyMe = 10,
		Friends = 20,
		Everyone = 30
	};

	enum SessionLoginBehavior {
		WebView,
		WebAuth,
		WebAccountProvider,
		DefaultOrdering,
		Silent
	};

	runtimeclass FacebookSession
	{
		FacebookSession();
		String FacebookAppId{ get; set; };
		String WinAppId{ get; set; };
		String AppResponse{ get; };
		Boolean LoggedIn{ get; };
		FacebookAccessTokenData AccessTokenData{ get; set; };
		Int32 APIMajorVersion{ get; };
		Int32 APIMinorVersion{ get; };
		winsdkfb.Graph.FBUser User{ get; };
		String WebViewRedirectDomain{ get; };
		String WebViewRedirectPath{ get; };
		static FacebookSession ActiveSession{ get; };
		static Windows.Storage.ApplicationDataContainer DataContainer{ get; };
		Windows.Foundation.IAsyncAction LogoutAsync();
		Windows.Foundation.IAsyncOperation<FacebookResult> ShowFeedDialogAsync(
			Windows.Foundation.Collections.PropertySet Parameters
		);
		Windows.Foundation.IAsyncOperation<FacebookResult> ShowRequestsDialogAsync(
			Windows.Foundation.Collections.PropertySet Parameters
		);
		Windows.Foundation.IAsyncOperation<FacebookResult> ShowSendDialogAsync(
			Windows.Foundation.Collections.PropertySet Parameters
		);
		Windows.Foundation.IAsyncOperation<winsdkfb.FacebookResult> LoginAsync();
		Windows.Foundation.IAsyncOperation<winsdkfb.FacebookResult> LoginAsync(winsdkfb.FacebookPermissions permissions);
		Windows.Foundation.IAsyncOperation<winsdkfb.FacebookResult> LoginAsync(winsdkfb.FacebookPermissions permissions, winsdkfb.SessionLoginBehavior behavior);

		void SetApiVersion(Int32 major, Int32 minor);
		void SetWebViewRedirectUrl(String domain, String Path);

		Windows.Foundation.IAsyncOperation<winsdkfb.FacebookResult> TryRefreshAccessTokenAsync();
	}
}
