import "FacebookPermissions.idl";

namespace winsdkfb
{
	runtimeclass FacebookAccessTokenData
	{
		static FacebookAccessTokenData FromUri(Windows.Foundation.Uri Response);
		FacebookAccessTokenData(String AccessToken, Windows.Foundation.DateTime Expiration);

		String AccessToken{ get; };
		Windows.Foundation.DateTime ExpirationDate{ get; };
		FacebookPermissions GrantedPermissions{ get; };
		FacebookPermissions DeclinedPermissions{ get; };
		Boolean IsExpired{ get; };
		void SetPermissions(Windows.Foundation.Collections.IVectorView<Object> perms);
	}
}
