namespace winsdkfb
{
	[default_interface]
	runtimeclass FBAppRequest
	{
		String RequestId{ get; };
		Windows.Foundation.Collections.IVectorView<String> RecipientIds{ get; };

		static FBAppRequest FromRequestDialogResponse(Windows.Foundation.Uri Response);
	}
}
