namespace winsdkfb
{
	[default_interface]
	runtimeclass FBMediaStream
	{
		FBMediaStream(String fileName, Windows.Storage.Streams.IRandomAccessStreamWithContentType stream);
		String FileName{ get; };
		Windows.Storage.Streams.IRandomAccessStreamWithContentType Stream{ get; };
	}
}
