namespace winsdkfb
{
	[default_interface]
	runtimeclass FBPermissions
	{
		FBPermissions(Windows.Foundation.Collections.IVectorView<String> Permissions);
		Windows.Foundation.Collections.IVectorView<String> Values{ get; };
		String ToString();
		static FBPermissions FromString(String Permissions);
		static FBPermissions Difference(FBPermissions Minuend, FBPermissions Subtrahend);
	}
}
