import "IHttpClient.idl";

namespace winsdkfb
{
	[default_interface]
	runtimeclass HttpManager : IHttpClient
	{
		static HttpManager Instance {get; };
		void SetHttpClient(IHttpClient httpClient);
	}
}
