namespace winsdkfb
{
	interface IHttpClient
	{
		Windows.Foundation.IAsyncOperation<String> GetTaskAsync(
			String path,
			Windows.Foundation.Collections.IMapView<String, Object> parameters
		);

		Windows.Foundation.IAsyncOperation<String> PostTaskAsync(
			String path,
			Windows.Foundation.Collections.IMapView<String, Object> parameters
		);

		Windows.Foundation.IAsyncOperation<String> DeleteTaskAsync(
			String path,
			Windows.Foundation.Collections.IMapView<String, Object> parameters
		);

		String ParametersToQueryString(
			Windows.Foundation.Collections.IMapView<String, Object> parameters
		);
	}
}
